const express = require('express')
const product = require('./routes/productRoute')
const user = require('./routes/userRoute')
const router = require('./routes/orderRoute')
const errorHandler = require('./middleware/error')
const {sendToken} = require('./extra')
const cookieParser = require('cookie-parser')
const app = express()
app.use(express.json())
app.use(cookieParser())
app.use('/api/v1',product)
app.use('/api/v1/user',user)
app.use('/api/v1/order',router)
app.use(errorHandler)
app.use(sendToken)
app.use(cookieParser())
app.use(function(req, res, next) {
    res.header("Access-Control-Allow-Origin", "http://localhost:3000")
    res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept")
    next()
})
module.exports = app